ipamsojt-Manalili-branch-Test-branch/ipams/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import debug_toolbar
from django.views.static import serve
from ipams import settings

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('', include('records.urls')),
    path('account/', include('accounts.urls')),
    path('notifications/', include('notifications.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

ipamsojt-Manalili-branch-Test-branch/notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'

urlpatterns = [
    path('student/', views.StudentNotification.as_view(), name='student_notifications'),
    path('adviser/', views.AdviserNotification.as_view(), name='adviser_notifications'),
    path('ktto/', views.KTTONotification.as_view(), name='ktto_notifications'),
    path('rdco/', views.RDCONotification.as_view(), name='rdco_notifications'),
    path('tbi/', views.TBINotification.as_view(), name='tbi_notifications'),
    path('itso/', views.ITSONotification.as_view(), name='itso_notifications'), 
]

ipamsojt-Manalili-branch-Test-branch/notifications/models.py
from django.db import models
from accounts.models import User, Student, UserRole
from records.models import Record
from ckeditor.fields import RichTextField

# Role Request Student, Role Request Adviser, New Record Proposal/Thesis, New Record Project, Resubmission, Role Request Approved
# Comments, Record Approved, Record Decline 
class NotificationType(models.Model):
    name = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='user') #who sent the notification

    course = models.CharField(
        blank=True, default='', null=True, max_length=255
    )  # student course if student 
    recipient = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='recipient') #who will receive the notification

    course = models.CharField(blank=True, null=True, max_length=255) # student course if student
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='recipient') #who will receive the notification

    role = models.ForeignKey(UserRole, on_delete=models.CASCADE, blank=True, null=True, default=7, related_name='role') # role of who sent the notification
    record = models.ForeignKey(Record, on_delete=models.CASCADE, blank=True, null=True, related_name='record') # current record if record
    notif_type = models.ForeignKey(NotificationType, on_delete=models.CASCADE, blank=True, null=True, related_name='notif_type') # type of notification
    read_by = models.ManyToManyField(User)
    to_ktto = models.BooleanField(default=False)
    to_rdco = models.BooleanField(default=False)
    is_read = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    def setUser(self, user):
        self.user = user

    def setCourse(self, course):
        self.course = course

    def setRecepient(self, recepient):
        self.recepient = recepient

    def setRole(self, role):
        self.role = role

    def setRecord(self, record):
        self.record = record

    def __str__(self):
        return self.notif_type.name

ipamsojt-Manalili-branch-Test-branch/notifications/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from accounts.decorators import authorized_roles, authorized_record_user
from django.db.models import Count, Subquery, Q, Sum

from accounts.models import User, Student, Course, UserRecord, UserRole, RoleRequest
from records.models import CheckedRecord
from .models import *
from notifications.auxfunctions import *
from records.auxfunctions import *

import datetime

class StudentNotification(View):
    name = 'notifications/student_notification_page.html'

    @method_decorator(authorized_roles(roles=['student']))
    @method_decorator(login_required(login_url='/'))
    def get(self, request):
        user = request.user
        notifications = Notification.objects.filter(recipient=user.id).order_by('-date_created')
        request.session['notif_count'] = notifications.count()
        return render(request, self.name, notificationDisplayStudent(request, notifications, 'Filter'))
    def post(self, request):
        if request.method == 'POST':
            user = request.user
            # for filter
            if 'all' in request.POST:
                notifications = Notification.objects.filter(recipient=user.id).order_by('-date_created')
                return render(request, self.name, filterHelperStudent(request, notifications, 'ALL'))
            elif 'read' in request.POST:
                notifications = Notification.objects.filter(Q(recipient=user.id) & Q(is_read=True)).order_by('-date_created')
                return render(request, self.name, filterHelperStudent(request, notifications, 'Read'))
            elif 'unread' in request.POST:
                notifications = Notification.objects.filter(Q(recipient=user.id) & Q(is_read=False)).order_by('-date_created')
                return render(request, self.name, filterHelperStudent(request, notifications, 'Unread'))
            elif 'approved' in request.POST:
                notifications = Notification.objects.filter(Q(recipient=user.id) & Q(notif_type=NotificationType.objects.get(pk=8))).order_by('-date_created')
                return render(request, self.name, filterHelperStudent(request, notifications, 'Approved'))
            elif 'declined' in request.POST:
                notifications = Notification.objects.filter(Q(recipient=user.id) & Q(notif_type=NotificationType.objects.get(pk=9))).order_by('-date_created')
                return render(request, self.name, filterHelperStudent(request, notifications, 'Declined'))

            if request.POST.get('removeNotification'):
                idList = request.POST.getlist('listOfID[]')
                for id in idList:
                    Notification.objects.get(pk=id).delete()
                return JsonResponse({'success': True})

            # content for each notification -> 2nd box content
            if request.POST.get('displayContent'):
                id = request.POST.get('notifID')
                Notification.objects.filter(pk=id).update(is_read=True)
                notifications = Notification.objects.filter(recipient=user.id)
                request.session['notif_count'] = notifications.count()
                notif = Notification.objects.get(pk=id)
                if notif.notif_type.name == 'Record Approved' or notif.notif_type.name == 'Record Decline':
                    record_status = CheckedRecord.objects.filter(record=notif.record_id).latest('status')
                    return JsonResponse(
                    {
                       'success': True,
                       'date': notif.date_created.strftime('%B %d, %Y, %#I:%M %p'),
                       'subject': notif.notif_type.name,
                       'title': notif.record.title,
                       'classification': notif.record.classification.name,
                       'psced': notif.record.psced_classification.name,
                       'recordID': notif.record_id,
                       'status': record_status.status,
                        'subject-body': notif.notif_type.name
                            + ' by '
                            + notif.user.first_name
                            + notif.user.last_name,
                            'checked-by': notif.user.first_name + ' ' + notif.user.last_name,
                            'authors': listOfAuthors(request, notif.record_id),
                        }
                    ) 
                    
                elif notif.notif_type.name == 'Role Request Approved':
                    return JsonResponse({'success': True,
                                        'fname': notif.recipient.first_name,
                                        'mname': notif.recipient.middle_name,
                                        'lname': notif.recipient.last_name,
                                        'username': notif.recipient.username,
                                        'email': notif.recipient.email,
                                        'date': notif.date_created.strftime('%B %d, %Y, %#I:%M %p'),
                                        'subject': notif.notif_type.name,
                                        'request': "Role Request Student",
                                        'subject-body':notif.notif_type.name+' by '+notif.user.first_name+notif.user.last_name,
                                        'approved-by': notif.user.first_name+' '+notif.user.last_name})

class AdviserNotification(View):
    name = 'notifications/adviser_notification_page.html'

    @method_decorator(authorized_roles(roles=['adviser']))
    @method_decorator(login_required(login_url='/'))
    def get(self, request):
        user = request.user
        notifications = Notification.objects.filter(Q(recipient=user.id) | Q(notif_type=NotificationType.objects.get(pk=6)) | Q(notif_type=NotificationType.objects.get(pk=1)) | Q(notif_type=NotificationType.objects.get(pk=2))).order_by('-date_created')
        request.session['notif_count'] = notifications.count()
        return render(request, self.name, notificationDisplay(request, notifications, 'Filter'))
    def post(self, request):
        if request.method == 'POST':
            user = request.user
            # for filter
            if 'all' in request.POST:
                notifications = Notification.objects.filter(Q(recipient=user.id) | Q(notif_type=NotificationType.objects.get(pk=6)) | Q(notif_type=NotificationType.objects.get(pk=1)) | Q(notif_type=NotificationType.objects.get(pk=2))).order_by('-date_created')
                return render(request, self.name, filterHelper(request, notifications, 'ALL'))
            elif 'read' in request.POST:
                notifications = Notification.objects.filter(Q(recipient=user.id) & Q(is_read=True)).order_by('-date_created')
                return render(request, self.name, filterHelper(request, notifications, 'Read'))
            elif 'unread' in request.POST:
                notifications = Notification.objects.filter(Q(recipient=user.id) & Q(is_read=False)).order_by('-date_created')
                return render(request, self.name, filterHelper(request, notifications, 'Unread'))
            elif 'rrs' in request.POST:
                notifications = Notification.objects.filter(Q(recipient=user.id) | Q(notif_type=NotificationType.objects.get(pk=1))).order_by('-date_created')
                return render(request, self.name, filterHelper(request, notifications, 'Role Request Student'))
            elif 'rra' in request.POST:
                notifications = Notification.objects.filter(Q(recipient=user.id) | Q(notif_type=NotificationType.objects.get(pk=2))).order_by('-date_created')
                return render(request, self.name, filterHelper(request, notifications, 'Role Request Adviser'))
            elif 'nrpt' in request.POST:
                notifications = Notification.objects.filter(Q(recipient=user.id) & Q(notif_type=NotificationType.objects.get(pk=3))).order_by('-date_created')
                return render(request, self.name, filterHelper(request, notifications, 'New Record Proposal/Thesis'))
            elif 'nrp' in request.POST:
                notifications = Notification.objects.filter(Q(recipient=user.id) & Q(notif_type=NotificationType.objects.get(pk=4))).order_by('-date_created')
                return render(request, self.name, filterHelper(request, notifications, 'New Record Project'))
            elif 'resubmission' in request.POST:
                notifications = Notification.objects.filter(Q(recipient=user.id) & Q(notif_type=NotificationType.objects.get(pk=5))).order_by('-date_created')
                return render(request, self.name, filterHelper(request, notifications, 'Resubmissions'))

            if request.POST.get('removeNotification'):
                idList = request.POST.getlist('listOfID[]')
                for id in idList:
                    Notification.objects.get(pk=id).delete()
                return JsonResponse({'success': True})

            if request.POST.get('roleChange'):
                role = request.POST.get('role')
                id = request.POST.get('id')
                User.objects.filter(pk=id).update(role=UserRole.objects.get(name=role))
                removeRequest = RoleRequest.objects.get(user=User.objects.get(pk=id))
                removeRequest.delete()
                roleRequestApproved(request, request.user.id, User.objects.get(pk=id).id)
                return JsonResponse({'success': True})

            # content for each notification -> 2nd box content
            if request.POST.get('displayContent'):
                id = request.POST.get('notifID')

ipamsojt-Manalili-branch-Test-branch/notifications/templates/notifications/index.html
{% extends 'ipams/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/notifications.css' %}"/>
<style type="text/css">
    #notification-header {
        float: right;
    }
</style>
{% endblock %}
{% block footer %}
    <script type="text/javascript">
        // change active class on dropdown buttons
        var header = document.getElementById("options");
        var btns = header.getElementsByClassName("dropdown-item");
        for (var i = 0; i < btns.length; i++) {
          btns[i].addEventListener("click", function() {
              var current = document.getElementsByClassName("active");
              current[0].className = current[0].className.replace(" active", "");
              this.className += " active";
          });
        }

        $(".saveID").on("click", function(e) {
            var id = $(this).attr('id').substr(-1);
            $(this).css('color', 'black');

            $("#task-form-"+id).on('submit', function(e) {
                e.preventDefault();
                $.ajax({
                    type:'POST',
                    url:"{% url 'notifications:rdco_notifications' %}",
                    data:
                    {
                        notifID: id,
                        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                    },
                    success: function(response){
                        $('#notification-body').html(''+response['subject']);
                    },
                })
            });
        });
    </script>
{% endblock%}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div id="notification-header" class="col-12 d-flex justify-content-center" style="margin-top:40px; margin-bottom:10px;">
                <!-- <ul>
                    <li><a href="#"></a></li>
                </ul> -->
                <div class="dropdown">
                  <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Filter
                  </button>
                  <div id="options" class="dropdown-menu" aria-labelledby="dropdownMenu2">
                    <button class="dropdown-item active" type="button">Action</button>
                    <li><hr class="dropdown-divider"></li>
                    <button class="dropdown-item" type="button">Another action</button>
                    <li><hr class="dropdown-divider"></li>
                    <button class="dropdown-item" type="button">Something else here</button>
                  </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="notifications-con">
                    <div id="notification-subjects">
                        {% for notification in notifications %}
                            {% if notification.is_read == 0 %}
                            <form method="post" id="task-form-{{ notification.id }}">
                            {% csrf_token %}
                                <ul> 
                                    <li>
                                        <button type="submit" class="saveID" id="btn-{{ notification.id }}" style="background:none; border:none; outline:none; cursor:pointer; color:red;"> {{ notification.notif_type }} </button>
                                    </li>
                                </ul>    
                            </form>
                            {% else %}
                            <ul> 
                                <li style="color: blacks;">   
                                    {{ notification.notif_type }}
                                </li>
                            </ul>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div id="notification-body">
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ipamsojt-Manalili-branch-Test-branch/notifications/templates/notifications/student_notification_page.html
{% extends 'ipams/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/notifications.css' %}"/>
<style type="text/css">
    #notification-header {
        float: right;
    }
    .header-title{
	font-size: 42px;
	font-weight: bold;
    }
</style>
{% endblock %}
{% block footer %}
    <script type="text/javascript">
        $("#deleteBtn").on('click', function(e) {
            var checkboxes = document.querySelectorAll('input[name="notification"]:checked');
            console.log(checkboxes);
            if(checkboxes.length == 0){
                Swal.fire({
                    type: 'warning',
                    title: 'No rows selected!',
                    html: 'You must first select a notification that you want to delete.',
                    showConfirmButton: true,
                })
            }
            else if(checkboxes.length != 0){
                $("#deleteModal").modal('show');
            }
        });
        
        $("#deleteConfirmModal").on("click", function(e){
            var checkboxes = document.querySelectorAll('input[name="notification"]:checked'), values = [];
            Array.prototype.forEach.call(checkboxes, function(cb) {
                values.push(cb.value);
            });

            $("#checklistform").on('submit', function(e){
                console.log(values);
                e.preventDefault();
                $.ajax({
                    type: 'POST',
                    url:"{% url 'notifications:ktto_notifications' %}",
                    data:
                    {
                        removeNotification: true,
                        listOfID: values,
                        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                    },
                    success: function(response){
                        window.location.reload(); 
                    }
                })
            });
        });

        $(".saveID").on("click", function(e) {
            var id = $(this).attr('id').split('-').pop();
            $(this).css('color', 'black');
            $("#taskform-"+id).on('submit', function(e) {
                e.preventDefault();
                $.ajax({
                    type:'POST',
                    url:"{% url 'notifications:student_notifications' %}",
                    data:
                    {
                        displayContent: true,
                        notifID: $(this).attr('id').split('-').pop(),
                        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                    },
                    success: function(response){
                        if(response['subject'] == 'Record Approved'){
                           $('#notification-body').html('<span>Subject: '+response['subject-body']+'</span><br><span>Date: '+response['date']+'</span><br><br><span>Title: '+response['title']+'</span><br><br><span>Author/s: '+response['authors']+'</span><br><br><span>Classification: '+response['classification']+'</span><br><br><span>Psced: '+response['psced']+'</span><br><br><span>Content: Record has been '+response['status']+' by '+response['checked-by']+'.</span><br><br><a href="/record/myrecords/'+response['recordID']+'">View Record</a>'); 
                        }
                        if(response['subject'] == 'Record Decline'){
                           $('#notification-body').html('<span>Subject: '+response['subject-body']+'</span><br><span>Date: '+response['date']+'</span><br><br><span>Title: '+response['title']+'</span><br><br><span>Author/s: '+response['authors']+'</span><br><br><span>Classification: '+response['classification']+'</span><br><br><span>Psced: '+response['psced']+'</span><br><br><span>Content: Record has been declined by '+response['checked-by']+'.</span><br><br><a href="/record/myrecords/'+response['recordID']+'">View Record</a>'); 
                        }
                        if(response['subject'] == 'Role Request Approved'){
                           $('#notification-body').html('<span>Subject: '+response['subject-body']+'</span><br><span>Date: '+response['date']+'</span><br><br><span>First name: '+response['fname']+'</span><br><br><span>Middle name: '+response['mname']+'</span><br><br><span>Last name: '+response['lname']+'</span><br><br><span>Username: '+response['username']+'</span><br><br><span>Request: '+response['request']+'</span><br><br><span>Content: Role Request has been approved by '+response['approved-by']+'</span><br>'); 
                        }

                    },
                })
            });
        });

        $(document).ready(function() {
            if('{{ subject }}' == 'Record Approved'){
               $('#notification-body').html('<span>Subject: {{ subject_body }}</span><br><span>Date: {{ date }}</span><br><br><span>Title: {{ title }}</span><br><br><span>Author/s: {{ authors }}</span><br><br><span>Classification: {{ classification }}</span><br><br><span>Psced: {{ psced }}</span><br><br><span>Content: Record has been {{ status }} by {{ checked_by }}.</span><br><br><a href="/record/myrecords/{{ recordID }}">View Record</a>'); 
            }
            if('{{ subject }}'== 'Record Decline'){
               $('#notification-body').html('<span>Subject: {{ subject_body }}</span><br><span>Date: {{ date }}</span><br><br><span>Title: {{ title }}</span><br><br><span>Author/s: {{ authors }}</span><br><br><span>Classification: {{ classification }}</span><br><br><span>Psced: {{ psced }}</span><br><br><span>Content: Record has been declined by {{ checked_by }}.</span><br><br><a href="/record/myrecords/{{ recordID }}">View Record</a>'); 
            }
            if('{{ subject }}' == 'Role Request Approved'){
               $('#notification-body').html('<span>Subject: {{ subject_body }}</span><br><span>Date: {{ date }}</span><br><br><span>First name: {{ fname }}</span><br><br><span>Middle name: {{ mname }}</span><br><br><span>Last name: {{ lname }}</span><br><br><span>Username: {{ username }}</span><br><br><span>Request: {{ request }}</span><br><br><span>Content: Role Request has been approved by {{ approved_by }}</span><br>'); 
            }
            var btns = document.getElementsByClassName("saveID");
            $(btns[0]).addClass("active");
        });

        var btnContainer = document.getElementById("notification-subjects");
        var btns = btnContainer.getElementsByClassName("saveID");
        for (var i = 0; i < btns.length; i++) {
            btns[i].addEventListener("click", function() {
                var current = document.getElementsByClassName("active");
                current[0].className = current[0].className.replace(" active", "");
                this.className += " active";
            });
        }
    </script>
{% endblock%}

{% block content %}
    <div class="container-fluid">

        <div class="header-title">
            <div class="row" style="margin-top: 30px; margin-left: 10px">
                <div class="col-12" style="margin-top: 30px; color:#550000">Notifications</div>
            </div>
        </div>
        
        <div class="row" style="margin-bottom: 20px;">
            <div id="notification-header" class="col-12 d-flex justify-content-center" style="margin-top:40px; margin-bottom:10px;">
                <form method="post" id="checklistform">
                    {% csrf_token %}
                    <input type="button" value="Delete" class="btn btn-danger" id="deleteBtn" style="position:absolute; left:250px;"/>
                    <!-- Delete Modal -->
                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title">Delete Confirmation</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <p>Delete selected notifications?</p>
                          </div>
                          <div class="modal-footer">
                            <button type="submit" class="btn btn-primary" id="deleteConfirmModal">Confirm</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                          </div>
                        </div>
                      </div>
                    </div>
                </form>
                <div class="btn-group dropleft" style="position:absolute; right:50px;">
                  <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ category }}
                  </button>
                  <div id="options" class="dropdown-menu" aria-labelledby="dropdownMenu2">
                    <form method="post">
                        {% csrf_token %}
                        <button class="dropdown-item" type="submit" name="all">ALL</button>
                        <li><hr class="dropdown-divider"></li>
                        <button class="dropdown-item" type="submit" name="read">Read</button>
                        <li><hr class="dropdown-divider"></li>
                        <button class="dropdown-item" type="submit" name="unread">Unread</button>
                        <li><hr class="dropdown-divider"></li>
                        <button class="dropdown-item" type="submit" name="approved">Approved</button>
                        <li><hr class="dropdown-divider"></li>
                        <button class="dropdown-item" type="submit" name="declined">Declined</button>
                    </form>
                  </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="notifications-con">
                    <div id="notification-subjects" style="overflow-y:scroll;">
                        {% for notification in notifications %}
                        <form method="post" id="taskform-{{ notification.id }}">
                        {% csrf_token %}
                            <div class="list-group list-group-flush">
                                    <button type="submit" class="saveID list-group-item list-group-item-action" id="btn-{{ notification.id }}"><input name="notification" type="checkbox" value="{{ notification.id }}" style="margin-right:30px;" />{{ notification.notif_type }}</button>
                                </div>      
                        </form>
                        {% endfor %}
                    </div>
                    <div class="col-8">
                        <div class="col-6">
                            <div id="notification-body">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}